Repository tum-ai/space, pull requests merged in 2024-01, with the labels that each got.

#185 feat: service for tally applications
  app/app/api/auth/[...nextauth].ts
  app/app/api/schema.dot
  app/app/api/schema.md
  app/app/api/tally/route.ts
  app/app/api/tally/routeTypes.ts
  app/app/api/user/route.ts
  app/app/env.mjs
  app/types/next-auth.d.ts
Labels: enhancement

#191 chore: GET ADD, UPDATE Admins and Screeners
  app/app/api/opportunities/[opportunityId] copy/admins/[adminId]/route.ts
  app/app/api/opportunities/[opportunityId] copy/admins/route.ts
  app/app/api/opportunities/[opportunityId] copy/screeners/[screenerId]/route.ts
  app/app/api/opportunities/[opportunityId] copy/screeners/route.ts
Labels: chore

#194 feat: Feat/dev 311 application review
  app/app/reviews/[opportunity_id]/components/ReviewInfoColumn.tsx
  app/app/reviews/[opportunity_id]/components/ReviewInputColumn.tsx
  app/app/reviews/[opportunity_id]/components/ReviewToolBar.tsx
  app/app/reviews/[opportunity_id]/page.tsx
  app/app/reviews/[opportunity_id]/review/[review_id]/page.tsx
  app/app/reviews/[opportunity_id]/review/components/InfoLabel.tsx
  app/app/reviews/components/ReviewsTable.tsx
  app/app/reviews/utils.ts
  app/components/ui/tabs.tsx
Labels: enhancement

#195 chore: Fix profile overview (Max Von Storch)
  app/app/me/[profile_id]/layout.tsx
  app/app/me/[profile_id]/page.tsx
  app/app/me/components/ProfileEditor.tsx
  app/app/me/components/ProfileOverview.tsx
  app/app/me/page.tsx
  app/app/profile/components/ProfileEditor.tsx
  app/app/profile/components/ProfileOverview.tsx
  app/models/profile.ts
Labels: chore

#198 feat:DEV-311-application review
  app/app/reviews/[opportunity_id]/components/ReviewInfoColumn.tsx
  app/app/reviews/[opportunity_id]/components/ReviewInputColumn.tsx
  app/app/reviews/[opportunity_id]/review/[review_id]/components/InfoLabel.tsx
  app/app/reviews/[opportunity_id]/review/[review_id]/components/ReviewInfoColumn.tsx
  app/app/reviews/[opportunity_id]/review/[review_id]/components/ReviewInputColumn.tsx
  app/app/reviews/[opportunity_id]/review/[review_id]/components/ReviewToolBar.tsx
  app/app/reviews/[opportunity_id]/review/[review_id]/components/inputs/InputCard.tsx
  app/app/reviews/[opportunity_id]/review/[review_id]/components/inputs/SelectCard.tsx
  app/app/reviews/[opportunity_id]/review/[review_id]/components/inputs/SliderCard.tsx
  app/app/reviews/[opportunity_id]/review/[review_id]/page.tsx
  app/app/reviews/[opportunity_id]/review/[review_id]/types.ts
  app/components/Textarea.tsx
  app/components/ui/slider.tsx
  app/components/ui/textarea.tsx
  app/package.json
Labels: enhancement

#199 feat: create applications overview
  app/app/opportunities/components/opportunityCard.tsx
  app/app/reviews/[opportunity_id]/components/OverviewRows.tsx
  app/app/reviews/[opportunity_id]/page.tsx
Labels: enhancement

#203 refactor: routing of OpportunityParticipation API endpoints
  app/app/api/opportunityParticipation/[opportunityId]/admins/[adminId]/route.ts
  app/app/api/opportunityParticipation/[opportunityId]/admins/route.ts
  app/app/api/opportunityParticipation/[opportunityId]/route.ts
  app/app/api/opportunityParticipation/[opportunityId]/screeners/[screenerId]/route.ts
  app/app/api/opportunityParticipation/[opportunityId]/screeners/route.ts
Labels: refactor

#202 feat: improve database schema to suit modular phase review management of opportunities
  app/prisma/schema.prisma
Labels: enhancement

#196 feat: create CRUD methods for DepartmentMembership
  app/app/api/departmentMemberships/[...departmentMembershipIds]/route.ts
  app/app/api/departmentMemberships/[departmentMembershipId]/route.ts
  app/app/api/departmentMemberships/route.ts
  app/app/api/departmentMemberships/userId/[userId]/departmentId/[departmentId]/route.ts
Labels: enhancement

#206 feat: add opportunity page retrieval endpoint
  app/app/opportunities/components/opportunityCard.tsx
  app/app/opportunities/page.tsx
  app/app/services/opportunityService.ts
Labels: enhancement
